name: plantin_test_project
description: "Mini gallery app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: 2.5.3
  get_it: 9.1.1
  go_router: 17.0.0
  provider: 6.1.5+1
  http: 1.6.0
  cached_network_image: 3.4.1
  image_picker: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
